Import the library.

In [119]:
import numpy as np
import pandas as pd

Read the dataset.

In [120]:
date = pd.read_csv('Datasets/orders.csv')
date.sample(5)

           date  product_id  city_id  orders
742  2018-07-15        3627       13      21
219  2019-07-26        4425       16       2
163  2018-11-12        2541       28       4
582  2019-07-22        1031        0       1
172  2019-06-24        5450       13       1

In [121]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [122]:
time = pd.read_csv('Datasets/messages.csv')
time.sample(5)

                    date                                                msg
58   2013-06-24 01:28:00  это просто кошмар! одни не мужики пошли! где н...
941  2014-01-06 00:40:00                           Брак Александр и Наталья
539  2014-05-31 01:58:00              сим П  26ищу Д для сер.отн.0985925276
435  2012-10-14 23:47:00             Красивая девушка на сей час 0935194947
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...

In [123]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Working with dates.

Convert object type date into datetime64.

In [124]:
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

Extract year.

In [125]:
date['date_year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  date_year
540 2018-09-26        7350       16      23       2018
640 2018-11-03        3161       21       1       2018
549 2018-11-11        6656       26      10       2018
16  2019-04-10         977       22       1       2019
596 2019-08-05        6091       25      92       2019

Extract semester and quater.

In [126]:
date['quarter'] = date['date'].dt.quarter
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  quarter  semester
0 2019-12-10       2019        4         2
1 2018-08-15       2018        3         2
2 2018-10-23       2018        4         2
3 2019-08-17       2019        3         2
4 2019-01-06       2019        1         1

Extract month number and name.

In [127]:
date['date_month_no'] = date['date'].dt.month
date.sample(5)

,date,product_id,city_id,orders,date_year,quarter,semester,date_month_no
89,2019-07-09,7214,22,4,2019,3,2,7
882,2019-10-14,5666,25,2,2019,4,2,10
386,2019-07-09,1935,2,37,2019,3,2,7
810,2019-06-25,1187,2,45,2019,2,1,6
776,2019-08-18,704,13,10,2019,3,2,8

In [128]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(5)

,date,product_id,city_id,orders,date_year,quarter,semester,date_month_no,date_month_name
629,2019-01-15,7138,28,1,2019,1,1,1,January
385,2018-07-24,4306,14,11,2018,3,2,7,July
503,2018-12-02,25,18,1,2018,4,2,12,December
476,2019-04-04,5979,21,2,2019,2,1,4,April
837,2018-12-15,5407,13,68,2018,4,2,12,December

Extract week of the year.

In [129]:
# date['date_week'] = date['date'].dt.week
date['date_week'] = date['date'].dt.isocalendar().week.astype('int32')

In [130]:
date['date_day'] = date['date'].dt.day
date.sample(5)

,date,product_id,city_id,orders,date_year,quarter,semester,date_month_no,date_month_name,date_week,date_day
742,2018-07-15,3627,13,21,2018,3,2,7,July,28,15
955,2018-11-05,5738,13,42,2018,4,2,11,November,45,5
492,2019-06-24,2306,14,12,2019,2,1,6,June,26,24
830,2019-03-14,3047,4,4,2019,1,1,3,March,11,14
74,2019-11-13,2199,14,2,2019,4,2,11,November,46,13

In [131]:
date['date_dow'] = date['date'].dt.day_name() # Day of week.
date.sample(5)

,date,product_id,city_id,orders,date_year,quarter,semester,date_month_no,date_month_name,date_week,date_day,date_dow
866,2019-11-27,1307,1,7,2019,4,2,11,November,48,27,Wednesday
235,2018-10-05,1288,20,22,2018,4,2,10,October,40,5,Friday
942,2019-11-16,2999,7,1,2019,4,2,11,November,46,16,Saturday
30,2019-07-24,2820,16,4,2019,3,2,7,July,30,24,Wednesday
490,2019-06-21,2254,16,4,2019,2,1,6,June,25,21,Friday

In [132]:
# day of week - name
date['date_dow_name'] = date['date'].dt.day_name()

# date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0) # Using numpy where function to find if saturday and sunday are in the column.

Extract time passed between dates.

In [133]:
import datetime

today = datetime.datetime.today()
# today.year
# today.month
# today.day
# today.weekday() # Monday is 0 and Sunday is 6.
today

datetime.datetime(2026, 3, 9, 18, 47, 54, 91314)

Find the days passed.

In [134]:
(today - date['date']).dt.days # Difference in days between today and the date column.

0      2281
1      2763
2      2694
3      2396
4      2619
       ...
995    2709
996    2650
997    2498
998    2563
999    2337
Name: date, Length: 1000, dtype: int64

Find the month passed.

In [135]:
(today.year - date['date'].dt.year) * 12 + (today.month - date['date'].dt.month)
# or np.round((today -date['date']) / np.timedelta64(1, 'M'),0)

0      75
1      91
2      89
3      79
4      86
       ..
995    89
996    87
997    82
998    84
999    77
Name: date, Length: 1000, dtype: int32

Work on the time dataset.

In [136]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

Change datatype to datetime64.

In [137]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

Create new column for hour, min, sec.

In [138]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

Extract time part from date column.

In [139]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

Find the time difference.

In [140]:
today - time['date'] # Difference between today and the date column in datetime format.

(today - time['date'])/np.timedelta64(1,'h') # Difference in hours between today and the date column.
(today - time['date'])/np.timedelta64(1,'m') # Difference in minutes between today and the date column.
(today - time['date'])/np.timedelta64(1,'s') # Difference in seconds between today and the date column.

0      3.860135e+08
1      3.742673e+08
2      4.162552e+08
3      3.559474e+08
4      3.902530e+08
           ...
995    4.412231e+08
996    3.825632e+08
997    4.227379e+08
998    4.327604e+08
999    3.698618e+08
Name: date, Length: 1000, dtype: float64